#!/bin/sh

# Create .config folder if it does not exist
mkdir -p $HOME/.config

# Install i3 config
ln -sf $(pwd)/config/i3/config $HOME/.config/i3/config

# Install and enable norwegian osx keyboard layout
sudo cp keyboard/no /usr/share/X11/xkb/symbols/no

