#!/bin/sh

# Create .config folder if it does not exist
mkdir -p $HOME/.config

# Disable plasma spash screen
if [ -f /usr/bin/ksplashqml ]; then
  sudo mv /usr/bin/ksplashqml /usr/bin/ksplashqml.old
fi

# Install and enable norwegian osx keyboard layout
sudo cp keyboard/no /usr/share/X11/xkb/symbols/no

# Install i3 config
mkdir -p $HOME/.config/i3
ln -sf $(pwd)/config/i3/config $HOME/.config/i3/config

# Install alacritty config
mkdir -p $HOME/.config/alacritty
ln -sf $(pwd)/config/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml

